#!/usr/bin/env node

import { homedir } from 'os';
import { join, dirname } from 'path';
import { mkdirSync, writeFileSync, existsSync } from 'fs';
import { execSync } from 'child_process';

const HOME = homedir();
const OPENCLAW_WORKSPACE = join(HOME, '.openclaw', 'workspace');
const TARGET_DIR = join(OPENCLAW_WORKSPACE, 'api-tester-skill');
const TOOLS_DIR = join(TARGET_DIR, 'tools');

// Check if OpenClaw is installed
if (!existsSync(OPENCLAW_WORKSPACE)) {
    console.error(`ERROR: OpenClaw workspace not found at ${OPENCLAW_WORKSPACE}`);
    console.error('Please install OpenClaw first (see https://github.com/openclaw/openclaw).');
    process.exit(1);
}

// Create directories
mkdirSync(TARGET_DIR, { recursive: true });
mkdirSync(TOOLS_DIR, { recursive: true });

console.log(`Installing API Tester Skill to ${TARGET_DIR}...`);

// File 1: tools/ingest_api.js
writeFileSync(join(TOOLS_DIR, 'ingest_api.js'), `import { exec } from 'child_process';
import util from 'util';
const execPromise = util.promisify(exec);
export async function run({ swagger_url }) {
    const outputDir = './api_workspace';
    try {
        await execPromise(\`npx openapi-to-skills "\${swagger_url}" -o \${outputDir} --force\`);
        return \`SUCCESS: Compiled to \${outputDir}. Read \${outputDir}/SKILL.md next.\`;
    } catch (error) { return \`ERROR: \${error.message}\`; }
}
`);

// File 2: tools/read_docs.js
writeFileSync(join(TOOLS_DIR, 'read_docs.js'), `import fs from 'fs';
import path from 'path';
export async function run({ file_path }) {
    try {
        const safePath = path.resolve(file_path);
        return fs.readFileSync(safePath, 'utf-8');
    } catch (error) { return \`ERROR: \${error.message}\`; }
}
`);

// File 3: tools/execute_test.js
writeFileSync(join(TOOLS_DIR, 'execute_test.js'), `export async function run({ url, method, headers = {}, payload = null }) {
    try {
        const options = { method: method.toUpperCase(), headers: { 'Content-Type': 'application/json', ...headers } };
        if (payload && (options.method === 'POST' || options.method === 'PUT')) { options.body = JSON.stringify(payload); }
        const response = await fetch(url, options);
        return JSON.stringify({ status: response.status, ok: response.ok, body: (await response.text()).substring(0, 1000) });
    } catch (error) { return \`EXECUTION ERROR: \${error.message}\`; }
}
`);

// File 4: SKILL.md
writeFileSync(join(TARGET_DIR, 'SKILL.md'), `# Universal Autonomous API Tester

## Purpose
This skill enables an agent to test any REST API systematically, using a three‑phase approach that ensures thoroughness, safety, and actionable reporting.

## Operating Procedure (Phase 3: Silent Execution)

### 1. Initialization
- Read the API specification (OpenAPI/Swagger) via **ingest_api** tool.
- Parse the SKILL.md generated by openapi‑to‑skills to understand endpoints, parameters, and expected behaviors.
- Build a test matrix covering all endpoints with varied payloads (valid, edge‑case, invalid).

### 2. Silent Execution & Selective Authentication Rules
- **The Auth Token:** Assume you have been provided a standard test token (e.g., \`Bearer TEST_TOKEN_123\`).
- **Safe Endpoints (GET, POST, PUT, PATCH):** If the API schema requires authentication, you MUST include the \`Authorization\` header in your \`execute_test\` request.
- **Destructive Endpoints (DELETE):** You MUST NOT send the \`Authorization\` header. Test these unauthenticated to verify the server's security. If the server returns a \`401 Unauthorized\` or \`403 Forbidden\`, mark this test as a **PASS** in your audit table, because the security is working correctly.
- **No intermediate output:** The agent must not log, print, or stream any test-step details or progress.
- **Execute sequentially:** Run each test case, capture results into the audit table, and proceed.

### 3. Final Audit Table
After all tests complete, the agent must output **exactly one** structured markdown table summarizing the entire test run.

**Format:**
| Endpoint | Method | Test Case | Status | Response Time (ms) | Error |
|----------|--------|-----------|--------|-------------------|-------|
| /users   | GET    | Valid request | PASS  | 145 | – |
| /users   | POST   | Missing required field | FAIL | 89 | "400 Bad Request" |

### 4. Post‑Execution
- If any critical failures (e.g., 5xx errors, authentication broken) are detected, append a brief recommendation section after the table.
- Do not add any extra commentary, summaries, or logs beyond the table and the optional recommendation.

## Tools

### ingest_api
- **Input:** { "swagger_url": "http://example.com/openapi.json" }
- **Action:** Downloads and compiles the OpenAPI spec into a local api_workspace directory.
- **Output:** Success message or error.

### read_docs
- **Input:** { "file_path": "./api_workspace/SKILL.md" }
- **Action:** Reads the content of a documentation file.
- **Output:** File content as string or error.

### execute_test
- **Input:** { "url": "http://api.example.com/users", "method": "GET", "headers": {}, "payload": null }
- **Action:** Performs an HTTP request and returns the response.
- **Output:** JSON string with status, ok, and truncated body.

## Usage Example
\`\`\`javascript
// Agent internal flow
1. await ingest_api({ swagger_url: "https://petstore.swagger.io/v2/swagger.json" });
2. const docs = await read_docs({ file_path: "./api_workspace/SKILL.md" });
3. For each endpoint in docs:
   await execute_test({ url: "...", method: "GET" });
4. Output final audit table.
\`\`\`

## Notes
- Ensure the environment has \`openapi-to-skills\` and \`node-fetch\` installed (the installer takes care of this).
- The agent must respect rate limits and use appropriate test data.
- All tests are non‑destructive where possible (use mock endpoints or sandbox environments).
`);

// Install required global packages
console.log('Installing required global packages (openapi-to-skills and node-fetch)...');
try {
    execSync('npm install -g openapi-to-skills', { stdio: 'inherit' });
} catch (e) {
    console.warn('Warning: Failed to install openapi-to-skills globally. You may need to install it manually.');
}
try {
    execSync('npm install -g node-fetch', { stdio: 'inherit' });
} catch (e) {
    console.warn('Warning: Failed to install node-fetch globally. You may need to install it manually.');
}

console.log('\n✅ API Tester Skill installed successfully!');
console.log('\nAdd the following line to your TOOLS.md:');
console.log('- **API Tester:** Located at `./api-tester-skill`. Read `./api-tester-skill/SKILL.md` to use.');
console.log('\nYou can now use the skill in your OpenClaw workspace.');
